Add more code samples and updated information for NextJS and NextAuth
gobeyondidentity/developer-docs pull request #297
Opened 2023-07-27 22:10 UTC by turnipdabeets

### Your checklist for this pull request

Thank you for your contribution to the `next-dev-docs` repo. 

🚨Please review the [Pull request guidelines](../contributor-guide/contributor-guide.md#pull-request-guidelines) to this repository before submitting this PR.

- [ x] Your code builds clean without any errors or warnings
  
  ```bash
  yarn build
  ```

- [ x] You are using approved terminology

  Refer to the [style guide](../contributor-guide/style-guide.md) for help.

### Description 

This PR fills out the `Integrate with NextAuth` and `Getting Started with NextJS` guides with more code samples, updated information, and filling out highlighted questions. Also in this PR is deleting an unused nextauth file.

2023-07-27 22:19 UTC, Will5 commented on docs/get-started/getting-started-nextjs.mdx
> +copy and paste the value from **Applications > {New Application} > External Protocol > Issuer**.
nit: copy should be capitalized

2023-07-27 22:26 UTC, Will5 commented on docs/get-started/getting-started-nextjs.mdx
> +    wellKnown: process.env.BEYOND_IDENTITY_DISCOVERY,
I love the simplification here 🙂

2023-07-28 03:27 UTC, turnipdabeets commented on docs/get-started/getting-started-nextjs.mdx
> +copy and paste the value from **Applications > {New Application} > External Protocol > Issuer**.
updated!

2023-07-31 16:39 UTC, patriciamcphee requested changes
Make sure you're following the guidelines outlined in the [style guide](https://github.com/gobeyondidentity/developer-docs/blob/docs-staging/contributor-guide/style-guide.md) and the [markdown reference guide](https://github.com/gobeyondidentity/developer-docs/blob/docs-staging/contributor-guide/markdown-reference.md).
-

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +3. If the URL is valid, we pull the URL using `window.location.href` and pass that directly into `embedded.bindPasskey` to complete the binding process.
Is there anything actionable in this sentence? If not, I would indent it under the first step.

Also, be careful with the use 'we'. If the user is doing something in this step, say 'you' and put the verb (action) at the beginning, so when they scan the content they'll know what this step does quickly.

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +If you are using Next.js version 13, create a `page.tsx` page under `/app/bi-authenticate/`.
```suggestion

```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +As long as your `Invoke URL` is configured properly in your [Authenticator Config](/docs/next/authentication), this is the page that will be redirected to during an authorization flow. Copy the follo
```suggestion
  As long as your `Invoke URL` is configured properly in your [Authenticator Config](/docs/next/authentication), this is the page that will be redirected to during an authorization flow. Copy the following code snippet into that page.
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +The authenticate URL that is redirected to your application will append a `/bi-authenticate` path to your Invoke URL. Create a `/bi-authenticate` route to intercept this URL in your application:
```suggestion
The authenticate URL that is redirected to your application will append a `/bi-authenticate` path to your Invoke URL. 
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
```suggestion

1. Create a `/bi-authenticate` route to intercept this URL in your application.
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
>  ```
```suggestion
  ```
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
>  ```
```suggestion
  ```
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +**Create a bi-authenticate route**:
```suggestion
2. Create a bi-authenticate route.
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +import { SessionProvider } from 'next-auth/react';
```suggestion
  import { SessionProvider } from 'next-auth/react';
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +    <SessionProvider session={pageProps.session} refetchInterval={0}>
```suggestion
      <SessionProvider session={pageProps.session} refetchInterval={0}>
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +      <Component {...pageProps} />
```suggestion
        <Component {...pageProps} />
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +  );
```suggestion
    );
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +}
```suggestion
  }
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +```
```suggestion
  ```
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +Note that `'beyondidentity'` in `signIn` is the id of the OAuth provider as configured in the providers array above.
```suggestion
  :::note
  `'beyondidentity'` in `signIn` is the ID of the OAuth provider as configured in the providers array above.
  :::
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +```javascript
```suggestion
  ```javascript
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +import { signIn, signOut, useSession } from 'next-auth/react';
```suggestion
  import { signIn, signOut, useSession } from 'next-auth/react';
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +const { data: session } = useSession();
```suggestion
  const { data: session } = useSession();
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +const [email, setEmail] = useState('');
```suggestion
  const [email, setEmail] = useState('');
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +  const { data: session, status } = useSession();
```suggestion
    const { data: session, status } = useSession();
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +  const [email, setEmail] = useState('');
```suggestion
    const [email, setEmail] = useState('');
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +  const handleRegistration = () => {
```suggestion
    const handleRegistration = () => {
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +    // to generate an identity and bind a passkey
```suggestion
      // to generate an identity and bind a passkey
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +  return (
```suggestion
    return (
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +        <div>
```suggestion
          <div>
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +          <p>{`Welcome ${session.user.name}!`}</p>
```suggestion
            <p>{`Welcome ${session.user.name}!`}</p>
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +        </div>
```suggestion
          </div>
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +      )}
```suggestion
        )}
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +      {!session && (
```suggestion
        {!session && (
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +            <button onClick={() => signIn('beyondidentity')}>Sign In</button>
```suggestion
              <button onClick={() => signIn('beyondidentity')}>Sign In</button>
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +              onChange={(event) => setEmail(event.target.value)}
```suggestion
                onChange={(event) => setEmail(event.target.value)}
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +            />
```suggestion
              />
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +}
```suggestion
  }
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +const handler = NextAuth({
```suggestion
  const handler = NextAuth({
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +    {
```suggestion
      {
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +      name: 'Beyond Identity',
```suggestion
        name: 'Beyond Identity',
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +      wellKnown: process.env.BEYOND_IDENTITY_DISCOVERY,
```suggestion
        wellKnown: process.env.BEYOND_IDENTITY_DISCOVERY,
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +      idToken: true,
```suggestion
        idToken: true,
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +      checks: ['state', 'pkce'],
```suggestion
        checks: ['state', 'pkce'],
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +          email: profile.sub,
```suggestion
            email: profile.sub,
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +        };
```suggestion
          };
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +export default async function Home() {
```suggestion
  export default async function Home() {
```

2023-07-31 16:39 UTC, patriciamcphee commented on docs/integration-guides/next-auth.md
> +  const session = await getServerSession(authOptions);
```suggestion
    const session = await getServerSession(authOptions);
```

2023-07-31 16:39 UTC, patriciamcphee requested changes
Make sure you're following the guidelines outlined in the [style guide](https://github.com/gobeyondidentity/developer-docs/blob/docs-staging/contributor-guide/style-guide.md) and the [markdown reference guide](https://github.com/gobeyondidentity/developer-docs/blob/docs-staging/contributor-guide/markdown-reference.md).
-

2023-07-31 20:15 UTC, patriciamcphee approved these changes

2023-07-31 20:16 UTC, merged