add content to AWS Cognito integration guide
gobeyondidentity/developer-docs pull request #306
Opened 2023-08-02 17:09 UTC by sublimezeal

### Your checklist for this pull request

Thank you for your contribution to the `next-dev-docs` repo. 

🚨Please review the [Pull request guidelines](../contributor-guide/contributor-guide.md#pull-request-guidelines) to this repository before submitting this PR.

- [X] Your code builds clean without any errors or warnings
  
  ```bash
  yarn build
  ```

- [X] You are using approved terminology

  Refer to the [style guide](../contributor-guide/style-guide.md) for help.

### Description 

Describe your pull request.

Adds content to the existing page for the AWS Integration Guide
Adds a new include for add a resource server.

2023-08-02 17:48 UTC, patriciamcphee requested changes

2023-08-02 17:48 UTC, patriciamcphee commented on docs/includes/_add-resource-server-console.mdx
```suggestion
1. First, click **Go to realm** and select the realm where you wish to create the resource server. This should be the realm of the application that you want to link to the resource server.  

2. Under **Authorization**, select **Resource Servers**.  

3. Click **Create resource server**.  
  ![Admin Console Create resource server window](../images/admin-console/create-resource-server.png)
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> + - Test the authorization code flow using the Amazon Cognito hosted UI
```suggestion
 - Test the authorization code flow using the Amazon Cognito-hosted UI
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> + - under **Domain**, choose Use a Cognito domain under **Domain type**
```suggestion
   1. Under **Domain**, select **Use a Cognito domain** under Domain type.
   
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> + - under **Allowed callback URLs** enter a callback URL for your app such as 'http://localhost:3000'
```suggestion
   1. Under **Allowed callback URLs**, enter a callback URL for your app, such as 'http://localhost:3000'.
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +5. In the **Connect federated identity providers** section, click Skip for now, then click Next. (We will add the OIDC provider after we create it below)
```suggestion
5. In the **Connect federated identity providers** section, click **Skip for now**, and then click **Next**.  You'll add add the OIDC provider after we create it later.  
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +### Create AWS as an OIDC client in Beyond Identity
```suggestion
### Create AWS as an OIDC client in Beyond Identity

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| PKCE | Disabled (Note that PKCE should be used where it is supported, but it is not a requirement for confidential clients.)|
```suggestion
| PKCE | Disabled (It's recommended to use PKCE where it is supported, but it is not a requirement for confidential clients.| 
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Resource Server | select the resource server you created above |
```suggestion
| Resource Server | Select the resource server you created above. | 
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Allowed Scopes | select scopes from the set of scopes assigned to the resource server you created above |
```suggestion
| Allowed Scopes | Select scopes from the set of scopes assigned to the resource server you created above. | 
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| all other options | use the default values for the remaining options |
```suggestion
| all other options | Use the default values for the remaining options. |  
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +1. Go to the [AWS Console](https://console.aws.amazon.com/cognito/home) and choose **User pools**
```suggestion
1. Go to the [AWS Console](https://console.aws.amazon.com/cognito/home) and select **User pools**.  
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +2. Select user pool you created above
```suggestion
2. Select the user pool you created earlier.
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +3. Click **Sign-in experience**
```suggestion
3. Click **Sign-in experience**.  
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +4. Under **Federated identity provider** click **Add identity provider**
```suggestion
4. Under **Federated identity provider**, click **Add identity provider**.
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +5. Under **Identity provider** select OpenID Connect (OIDC)
```suggestion
5. Under **Identity provider**, select OpenID Connect (OIDC).
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> + - Enter a **Provider name** (note that the name cannot have spaces)
```suggestion
   - Enter a **Provider name** (the name cannot have spaces).
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> + - For **Client ID**, enter the **Client ID** from the Beyond Identity app you created above
```suggestion
   - For **Client ID**, enter the **Client ID** from the Beyond Identity app you created earlier.
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> + - For **Client secret**, enter the **Client Secret** from the Beyond Identity app you created above
```suggestion
   - For **Client secret**, enter the **Client Secret** from the Beyond Identity app you created earlier.
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> + - for **Authorized scopes** enter `openid` followed by other scopes you wish to request, space delimited, for example `openid aws:customclaim`
```suggestion
   - For **Authorized scopes**, enter `openid` followed by other scopes you want to request, space delimited, for example, `openid aws:customclaim`.
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> + - For **Issuer URL** enter the **Issuer** value from the Beyond Identity app you created above
```suggestion
   - For **Issuer URL**, enter the **Issuer** value from the Beyond Identity app you created earlier.
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +6. Under **Map attributess...**, for the required attribute 'email', enter **OpenID Connect attribute** `sub`.
```suggestion
6. Under **Map attributes**, for the required attribute 'email', enter **OpenID Connect attribute** `sub`.
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +7. Click **Add identity provider**
```suggestion
7. Click **Add identity provider**.
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +## Update Hosted UI to point to the new Federated Provider
```suggestion
## Update Hosted UI to point to the new Federated Provider

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +Now, you will connect your user pool's app client to the OIDC provider you created above.
```suggestion
Now, you'll connect your user pool's app client to the OIDC provider you created earlier.  
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +1. Go to [AWS Console](https://console.aws.amazon.com/cognito/home) and choose **User pools**
```suggestion
1. Go to [AWS Console](https://console.aws.amazon.com/cognito/home) and select **User pools**.  

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +2. Select the user pool you created above
```suggestion
2. Select the user pool you created earlier.

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +3. Click the **App integration** tab
```suggestion
3. Click the **App integration** tab.

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +4. Scroll down to **App client list** and select your App client
```suggestion
4. Scroll down to **App client list** and select your App client.

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +5. Scroll down to **Hosted UI** and click Edit
```suggestion
5. Scroll down to **Hosted UI** and click Edit.

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +6. Under **Identity providers**, in the drop down list for **Select identity providers**. select the federated provider you created above
```suggestion
6. Under **Identity providers**, in the drop down list for **Select identity providers**. select the federated provider you created earlier.

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +7. Click **Save changes**
```suggestion
7. Click **Save changes**.

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +## Test OIDC connection
```suggestion
## Test OIDC connection

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +Next, your app will need to exchange that code for an access token and optionally id token and refresh token.
```suggestion
Next, your app must exchange that code for an access token, optionally an ID token and a refresh token.  

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +Now you will use AWS Cognito's "Hosted UI" test tool to test the integration.
```suggestion
Now you'll use AWS Cognito's "Hosted UI" test tool to test the integration.  
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +1. Go to the [AWS Console](https://console.aws.amazon.com/cognito/home) and choose **User pools**
```suggestion
1. Go to the [AWS Console](https://console.aws.amazon.com/cognito/home) and select **User pools**.

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +2. Select the user pool you created above
```suggestion
2. Select the user pool you created earlier.

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +3. Click the **App integration** tab
```suggestion
3. Click the **App integration** tab.

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +4. Scroll down to **App client list** and select your App client
```suggestion
4. Scroll down to **App client list** and select your App client.

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +5. Under **Hosted UI** click **View Hosted UI**
```suggestion
5. Under **Hosted UI**, click **View Hosted UI**.
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +[Adding OIDC identity providers to a user pool](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-oidc-idp.html)
```suggestion

- [Adding OIDC identity providers to a user pool](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-oidc-idp.html)   

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +[Create a user pool](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-as-user-directory.html)
```suggestion
- [Create a user pool](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-as-user-directory.html)  

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +[Add an app client and set up the hosted UI](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-configuring-app-integration.html)
```suggestion
- [Add an app client and set up the hosted UI](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-configuring-app-integration.html)  
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +Next, you will create a new realm and switch to that realm in your tenant. A realm is just a logical grouping that helps you apply policy later.
```suggestion
Next, you'll create a new realm and switch to that realm in your tenant. A realm is just a logical grouping that helps you apply policy later.   
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +The AWS user pool will connect your AWS apps to the Beyond Identity OIDC provider. Follow the steps below to create the user pool.
```suggestion
The AWS user pool connects your AWS apps to the Beyond Identity OIDC provider. Follow the steps below to create the user pool.  
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +2. Choose **Create user pool**
```suggestion
2. Select **Create user pool**.

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +3. In the **Configure sign-in experience** section:
```suggestion
3. In the **Configure sign-in experience** section, do the following:

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +4. In the **Configure security requirements** section:
```suggestion
4. In the **Configure security requirements** section, under **MFA methods**, select Authenticator apps.

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +6. In the **Integrate your app** section:
```suggestion
6. In the **Integrate your app** section, do the following:

```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +In this section, you will create a resource server and app in your Beyond Identity realm to represent AWS Cognito.
```suggestion
In this section, you'll create a resource server and app in your Beyond Identity realm to represent AWS Cognito.
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Resource Server Identifier |  Enter a unique identifier such as 'awsresourceserver'. This identifier will be included as the audience claim in access tokens minted for your application.  |
```suggestion
| Resource Server Identifier |  Enter a unique identifier such as 'awsresourceserver'. This identifier is included as the audience claim in access tokens minted for your application.  |
```

2023-08-02 17:48 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +In this section, you will configure your AWS user pool with an OIDC connection to the Beyond Identity app you created above.
```suggestion
In this section, you'll configure your AWS user pool with an OIDC connection to the Beyond Identity app you created earlier.  
```

2023-08-02 18:10 UTC, patriciamcphee reviewed
@sublimezeal I did a copy edit and committed those changes.

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +Configure the [app](/docs/next/add-an-application) with the following properties:
```suggestion
1. Configure the [app](/docs/next/add-an-application) with the following properties:  
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Parameter | Value|
```suggestion
   | Parameter | Value|
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +|---|---|
```suggestion
   |---|---|  
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Display Name | any name you choose |
```suggestion
   | Display Name | any name you choose |
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Protocol | OIDC |
```suggestion
   | Protocol | OIDC |
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Client Type | Confidential |
```suggestion
   | Client Type | Confidential | 
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| PKCE | Disabled (It's recommended to use PKCE where it is supported, but it is not a requirement for confidential clients.|
```suggestion
   | PKCE | Disabled (It's recommended to use PKCE where it is supported, but it is not a requirement for confidential clients.| 
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Redirect URIs | https://your-user-pool-domain/oauth2/idpresponse, where your-user-pool-domain can be found on your AWS User pool's **App integration** tab under **Domain**|
```suggestion
   | Redirect URIs | https://your-user-pool-domain/oauth2/idpresponse, where your-user-pool-domain can be found on your AWS User pool's **App integration** tab under **Domain**|   
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Token Endpoint Auth Method | Client Secret Basic |
```suggestion
   | Token Endpoint Auth Method | Client Secret Basic | 
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Grant Type | Authorization Code |
```suggestion
   | Grant Type | Authorization Code | 
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Resource Server | Select the resource server you created above. |
```suggestion
   | Resource Server | Select the resource server you created above. | 
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Allowed Scopes | Select scopes from the set of scopes assigned to the resource server you created above. |
```suggestion
   | Allowed Scopes | Select scopes from the set of scopes assigned to the resource server you created above. | 
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Subject  (under **Token Configuration**) | email |
```suggestion
   | Subject  (under **Token Configuration**) | email |  
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| Configuration Type (on the **Authenticator Config** tab) | Hosted Web |
```suggestion
   | Configuration Type (on the **Authenticator Config** tab) | Hosted Web |  
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +| all other options | Use the default values for the remaining options. |
```suggestion
   | all other options | Use the default values for the remaining options. |  
```

2023-08-02 18:23 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +Click **Submit** to save the app.
```suggestion
1. Click **Submit** to save the app.  
```

2023-08-02 18:27 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +2. Now that you have your tenant, log in. You can access the Beyond Identity Admin Console for your tenant at [BI admin console US](https://console-us.beyondidentity.com/login) or [BI admin console E
```suggestion

2. Now that you have your tenant, log in. You can access the Beyond Identity Admin Console for your tenant at [BI admin console US](https://console-us.beyondidentity.com/login) or [BI admin console EU](https://console-eu.beyondidentity.com/login), depending on the region you chose when you signed up.   
```

2023-08-02 18:27 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +2. Now that you have your tenant, log in. You can access the Beyond Identity Admin Console for your tenant at [BI admin console US](https://console-us.beyondidentity.com/login) or [BI admin console E
```suggestion

2. Now that you have your tenant, log in. You can access the Beyond Identity Admin Console for your tenant at [BI admin console US](https://console-us.beyondidentity.com/login) or [BI admin console EU](https://console-eu.beyondidentity.com/login), depending on the region you chose when you signed up.   
```

2023-08-02 18:30 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +6. Under **Identity providers**, in the drop down list for **Select identity providers**. select the federated provider you created earlier.
```suggestion
6. Under **Identity providers**, in the drop down list for **Select identity providers**, select the federated provider you created earlier.
```

2023-08-02 19:03 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +As a result of the test above, you should have an authorization code returned to your app client's redirect URI, such as 'http://localhost:3000/?code={authorization_code}
```suggestion

```

2023-08-02 19:03 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +
```suggestion

As a result of the test above, you should have an authorization code returned to your app client's redirect URI, such as 'http://localhost:3000/?code={authorization_code}'.

```

2023-08-02 19:04 UTC, patriciamcphee commented on docs/integration-guides/aws-cognito.md
> +As a result of the test above, you should have an authorization code returned to your app client's redirect URI, such as 'http://localhost:3000/?code={authorization_code}'.
```suggestion
As a result of this test, you should have an authorization code returned to your app client's redirect URI, such as 'http://localhost:3000/?code={authorization_code}'.
```

2023-08-09 14:58 UTC, Will5 approved these changes
Did not test, but it looks good to me

2023-08-14 17:12 UTC, nmelo approved these changes
LGTM!

2023-08-16 18:44 UTC, merged